# Generated by Django 2.0.5 on 2020-04-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_user_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_like',
            new_name='users_like',
        ),
    ]
